@host=localhost:80
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIiwiZ2l2ZW5fbmFtZSI6IlVzZXIiLCJmYW1pbHlfbmFtZSI6IlVzZXIiLCJqdGkiOiJhZDgwNjA3ZC01NmI2LTQ4ODgtODhjMi0xMWYyZTc4ODg5OGQiLCJleHAiOjIwNDE4MTAxOTksImlzcyI6IkhpZ2hsb2FkU29jaWFsIiwiYXVkIjoiSGlnaGxvYWRTb2NpYWwifQ.us6xdtTtsNiKOcIkjXO_XNM8FAXiL6zxFjd2WQpW5lk
### Login
POST http://{{host}}/login
Content-Type: application/json

{
  "id": "User",
  "password": "password"
}

### List friends
GET http://{{host}}/friend/list
Content-Type: application/json
Authorization: Bearer {{token}}


### Delete friend
PUT http://{{host}}/friend/delete/AccountLess3602
Content-Type: application/json
Authorization: Bearer {{token}}

### Set friend
PUT http://{{host}}/friend/set/AccountLess3602
Content-Type: application/json
Authorization: Bearer {{token}}