@host=localhost:80
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIiwiZ2l2ZW5fbmFtZSI6IlVzZXIiLCJmYW1pbHlfbmFtZSI6IlVzZXIiLCJqdGkiOiIwMzZkN2QzYS0zM2ViLTRiYTctOGFiNy03OGQ3Y2Y4NzVmNzIiLCJleHAiOjIwNDE4MTA1MzEsImlzcyI6IkhpZ2hsb2FkU29jaWFsIiwiYXVkIjoiSGlnaGxvYWRTb2NpYWwifQ.2_X_7S9GG6A9kI8e0amOFOD0ccPlB6R280lyxq-ywEY

### Login
POST http://{{host}}/login
Content-Type: application/json

{
  "id": "User",
  "password": "password"
}

### List
GET http://{{host}}/post/list
Content-Type: application/json
Authorization: Bearer {{token}}

### Feed
GET http://{{host}}/post/feed?offset=100&limit=25
Content-Type: application/json
Authorization: Bearer {{token}}

### GetById
GET http://{{host}}/post/get/448a3697-cdf4-4a8d-ac7e-3106f622e39a
Content-Type: application/json
Authorization: Bearer {{token}}

### Delete
PUT http://{{host}}/post/delete/
Content-Type: application/json
Authorization: Bearer {{token}}

### Create
POST http://{{host}}/post/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text": "Lorem Ipsum"
}